//
// Created by abdir on 30/11/2025.
//

#ifndef MACHINE_BEREKENBAARHEID_GROEPS_OPDRACHT_SLR_H
#define MACHINE_BEREKENBAARHEID_GROEPS_OPDRACHT_SLR_H


class SLR {

};


#endif //MACHINE_BEREKENBAARHEID_GROEPS_OPDRACHT_SLR_H
